<?php

use Illuminate\Database\Seeder;

class AlbumsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('albums')->insert([
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 9,
                'user_id'   => 5,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 10,
                'user_id'   => 6,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 11,
                'user_id'   => 7,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 12,
                'user_id'   => 8,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 13,
                'user_id'   => 9,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 14,
                'user_id'   => 10,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 15,
                'user_id'   => 11,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 16,
                'user_id'   => 12,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 17,
                'user_id'   => 13,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 18,
                'user_id'   => 14,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 19,
                'user_id'   => 15,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 20,
                'user_id'   => 16,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 21,
                'user_id'   => 17,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 22,
                'user_id'   => 18,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 23,
                'user_id'   => 19,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 24,
                'user_id'   => 20,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 25,
                'user_id'   => 21,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 26,
                'user_id'   => 22,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 27,
                'user_id'   => 23,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 28,
                'user_id'   => 24,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 29,
                'user_id'   => 25,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 30,
                'user_id'   => 26,
                'content' => json_encode([
                    ['title' => '1.png', 'photo_id' => 9, 'href' => '1.png'],
                    ['title' => '2.png', 'photo_id' => 10, 'href' => '2.png'],
                    ['title' => '3.png', 'photo_id' => 11, 'href' => '3.png'],
                    ['title' => '4.png', 'photo_id' => 12, 'href' => '4.png'],
                    ['title' => '5.png', 'photo_id' => 13, 'href' => '5.png'],
                    ['title' => '6.png', 'photo_id' => 14, 'href' => '6.png'],
                    ['title' => '7.png', 'photo_id' => 15, 'href' => '7.png'],
                    ['title' => '8.png', 'photo_id' => 16, 'href' => '8.png'],
                    ['title' => '9.png', 'photo_id' => 17, 'href' => '9.png'],
                    ['title' => '10.png', 'photo_id' => 18, 'href' => '10.png'],
                    ['title' => '11.png', 'photo_id' => 19, 'href' => '11.png'],
                    ['title' => '12.png', 'photo_id' => 20, 'href' => '12.png'],
                    ['title' => '13.png', 'photo_id' => 21, 'href' => '13.png'],
                    ['title' => '14.png', 'photo_id' => 22, 'href' => '14.png'],
                    ['title' => '15.png', 'photo_id' => 23, 'href' => '15.png'],
                    ['title' => '16.png', 'photo_id' => 24, 'href' => '16.png'],
                    ['title' => '17.png', 'photo_id' => 25, 'href' => '17.png'],
                    ['title' => '18.png', 'photo_id' => 26, 'href' => '18.png'],
                    ['title' => '19.png', 'photo_id' => 27, 'href' => '19.png'],
                    ['title' => '20.png', 'photo_id' => 28, 'href' => '20.png'],
                    ['title' => '21.png', 'photo_id' => 29, 'href' => '21.png'],
                    ['title' => '22.png', 'photo_id' => 30, 'href' => '22.png'],
                ]),
                'type'  => 'photo'
            ],
            [
                'name'   => 'Weplanner video album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 1,
                'user_id'   => 5,
                'content' => json_encode([
                    ['title' => 'video_1', 'video_id' => 2, 'href' => 'video.mp4']
                ]),
                'type'  => 'video'
            ],
            [
                'name'   => 'Weplanner audio album',
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dolorem harum minus optio. Consectetur dolores dolorum est impedit minus nemo velit veniam.',
                'cover' => 1,
                'user_id'   => 5,
                'content' => json_encode([
                    ['title' => 'audio_1', 'audio_id' => 3, 'href' => 'audio.mp4']
                ]),
                'type'  => 'audio'
            ],
        ]);
    }
}
