<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Db::table('categories')->insert([
            ['name' => 'Видео','name_en' => 'Video','slug' => 'video','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Ведущие','name_en' => 'Presenters','slug' => 'presenters','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Диджеи','name_en' => 'DJ','slug' => 'dj','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Площадки','name_en' => 'Venues','slug' => 'venues','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Техническое обеспечение','name_en' => 'Technical support','slug' => 'tech-support','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Музыкальная программа','name_en' => 'Music program','slug' => 'mus-prog','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Шоу программа','name_en' => 'Show program','slug' => 'show-prog','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Подарки','name_en' => 'Souvenirs','slug' => 'souvenirs','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Звук','name_en' => 'Audio','slug' => 'audio','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Танцевальная программа','name_en' => 'Dance program','slug' => 'dance-prog','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Артисты','name_en' => 'Artists','slug' => 'artists','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Транспорт','name_en' => 'Transport','slug' => 'transport','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Аренда','name_en' => 'Rent','slug' => 'rent','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Сотрудники','name_en' => 'Staff','slug' => 'staff','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Дизайн и декор','name_en' => 'Design & Decor','slug' => 'decor','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Цветы','name_en' => 'Flowers','slug' => 'flowers','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Другое','name_en' => 'Other','slug' => 'other','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Питание','name_en' => 'Catering','slug' => 'catering','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Торты и кондитерские изделия','name_en' => 'Cakes and confectioner','slug' => 'cakes','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Мужская одежда','name_en' => 'Men\'s Clothing','slug' => 'men-clothing','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Аксессуары','name_en' => 'Clothing akksesuary','slug' => 'clothing-acces','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Красота и здоровье','name_en' => 'Beauty and Health','slug' => 'beauty','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Ювелирные изделия','name_en' => 'Jewelery','slug' => 'jewelery','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Фотографы','name_en' => 'Photography','slug' => 'photo','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
        ]);
    }
}
