<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Db::table('categories')->insert([
            ['name' => 'Видео', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Video','slug' => 'video','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Ведущие', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Presenters','slug' => 'presenters','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Диджеи', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'DJ','slug' => 'dj','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Площадки', 'currency' => 'человека', 'currency_en' => 'guest','name_en' => 'Venues','slug' => 'venues','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Техобеспечение', 'currency' => 'день', 'currency_en' => 'day','name_en' => 'Technical support','slug' => 'tech-support','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Музыка', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Music program','slug' => 'mus-prog','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Шоу программа', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Show program','slug' => 'show-prog','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Подарки', 'currency' => 'чек', 'currency_en' => 'check','name_en' => 'Souvenirs','slug' => 'souvenirs','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Звук', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Audio','slug' => 'audio','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Танцоры', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Dance program','slug' => 'dance-prog','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Артисты', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Artists','slug' => 'artists','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Транспорт', 'currency' => 'км.', 'currency_en' => 'km.','name_en' => 'Transport','slug' => 'transport','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Аренда', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Rent','slug' => 'rent','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Сотрудники', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Staff','slug' => 'staff','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Дизайн и декор', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Design & Decor','slug' => 'decor','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Цветы', 'currency' => 'букет', 'currency_en' => 'bouquet','name_en' => 'Flowers','slug' => 'flowers','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Другое', 'currency' => 'товар', 'currency_en' => 'product','name_en' => 'Other','slug' => 'other','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Питание', 'currency' => 'человека', 'currency_en' => 'guest','name_en' => 'Catering','slug' => 'catering','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Кондитерские изделия', 'currency' => 'товар', 'currency_en' => 'product','name_en' => 'Cakes and confectioner','slug' => 'cakes','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Мужская одежда', 'currency' => 'товар', 'currency_en' => 'product','name_en' => 'Men\'s Clothing','slug' => 'men-clothing','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Аксессуары', 'currency' => 'товар', 'currency_en' => 'product','name_en' => 'Clothing akksesuary','slug' => 'clothing-acces','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Красота и здоровье', 'currency' => 'чек', 'currency_en' => 'check','name_en' => 'Beauty and Health','slug' => 'beauty','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Ювелирные изделия', 'currency' => 'товар', 'currency_en' => 'product','name_en' => 'Jewelery','slug' => 'jewelery','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['name' => 'Фотографы', 'currency' => 'час', 'currency_en' => 'hour','name_en' => 'Photography','slug' => 'photo','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
        ]);
    }
}
