<?php

use Illuminate\Database\Seeder;

class TermTaxonomyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Db::table('term_taxonomy')->insert([
            ['term_taxonomy_id' => '1','term_id' => '1','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '2','term_id' => '2','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '3','term_id' => '3','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '4','term_id' => '4','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '5','term_id' => '5','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '6','term_id' => '6','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '7','term_id' => '7','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '8','term_id' => '8','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '9','term_id' => '9','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '10','term_id' => '10','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '11','term_id' => '11','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '12','term_id' => '12','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '13','term_id' => '13','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '14','term_id' => '14','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '15','term_id' => '15','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '16','term_id' => '16','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '17','term_id' => '17','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '18','term_id' => '18','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '19','term_id' => '19','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '20','term_id' => '20','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '21','term_id' => '21','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '22','term_id' => '22','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '23','term_id' => '23','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '24','term_id' => '24','taxonomy' => 'category','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','description_en' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa cum dolor laborum laudantium modi nostrum possimus quos sed soluta.','parent' => '0','count' => '0'],
            ['term_taxonomy_id' => '34','term_id' => '34','taxonomy' => 'img_tag','description' => '','description_en' => '','parent' => '0','count' => '1'],
            ['term_taxonomy_id' => '35','term_id' => '35','taxonomy' => 'img_tag','description' => '','description_en' => '','parent' => '0','count' => '3'],
            ['term_taxonomy_id' => '36','term_id' => '36','taxonomy' => 'news','description' => 'Lorem Ipsum боль сидят Амет, consectetur adipiscing Элит. Pellentesque Новичок лациния Хусто, Новичок euismod дуй. Nulla биография pellentesque augue, Quis vulputate nibh. Fusce efficitur Lectus Метус, ID dignissim сем imperdiet Eget. Нам Лев миль, TEMPOR Tellus др, sodales finibus mauris.','description_en' => 'ເດືອນສໍາຄັນ, ເຮົາເປັນ. justo Pellentesque ຫຼື lacinia, dui Euismod ຫຼື. ຫົວ augue Pellentesque ເຫລົ້າ, quis vulputate ຕິດຕາມ. Fusce efficitur lectus metu, ຫນວດຫມູ່ id sem imperdiet eget. ນ້ໍາ leo mi, Tempor ເປັນ tellus et, sodales finibus ຕິດຕາມ.','parent' => '0','count' => '4'],
            ['term_taxonomy_id' => '37','term_id' => '37','taxonomy' => 'news','description' => 'Lorem Ipsum боль сидят Амет, consectetur adipiscing Элит. Pellentesque Новичок лациния Хусто, Новичок euismod дуй. Nulla биография pellentesque augue, Quis vulputate nibh. Fusce efficitur Lectus Метус, ID dignissim сем imperdiet Eget. Нам Лев миль, TEMPOR Tellus др, sodales finibus mauris.','description_en' => '','parent' => '0','count' => '1'],
            ['term_taxonomy_id' => '38','term_id' => '38','taxonomy' => 'news','description' => 'Home dolor zauna amet, consectetur adipiscing elit. Pellentesque vel lacinia justo, vel euismod DUI. Nulla vitae pellentesque augue, quis vulputate nibh. Fusce efficitur lectus metus, id dignissim SEM imperdiet eget. Nam Leo mi, tempor a tellus et, sodales finibus mauris.','description_en' => '','parent' => '0','count' => '2'],
            ['term_taxonomy_id' => '39','term_id' => '39','taxonomy' => 'news','description' => 'Lorem ipsum मातम, amet consectetur adipiscing elit बस्न। Pellentesque vel lacinia justo, vel euismod DUI। Nulla VITAE pellentesque augue, quis vulputate nibh। Fusce efficitur lectus metus, आईडी dignissim SEM imperdiet eget। भियतनाम Leo मील, tempor एक tellus एट, sodales finibus mauris।','description_en' => '','parent' => '0','count' => '1'],
            ['term_taxonomy_id' => '40','term_id' => '40','taxonomy' => 'news','description' => 'ເດືອນສໍາຄັນ, ເຮົາເປັນ. justo Pellentesque ຫຼື lacinia, dui Euismod ຫຼື. ຫົວ augue Pellentesque ເຫລົ້າ, quis vulputate ຕິດຕາມ. Fusce efficitur lectus metu, ຫນວດຫມູ່ id sem imperdiet eget. ນ້ໍາ leo mi, Tempor ເປັນ tellus et, sodales finibus ຕິດຕາມ.','description_en' => '','parent' => '0','count' => '1']
        ]);
    }
}
